### ISSUE TITLE
sectioning for activity fields

### ISSUE THREAD

**Issue by tiffany-slac** [eed-web-application/core-work-management#41]
### General Task 

**General Information:** 
- Task Priority 
- Task Skill Set 
- Percentage Completed 
**Other:**
- Module 
- Old Serial Number 
- New Serial Number 
- Drawing 
- Doc Solution 
- Date RTC Checked 
- Feedback Priority 

### Software Task 

**Scheduling** 
- Scheduling Priority 
- Time Comments 
**Requirements** 
- Access Requirements 
- Beam Requirements 
- Beam Comment 
- Invasive 
- Invasive Comment 
**Plan**
- Test Plan 
- Backout Plan 
- Systems Required 
- Systems Affected 
- Risk Benefit 
- Dependencies 
**Status** 
- CD Review Date 

### Hardware Task 

**Scheduling** 
- Scheduling Priority 
**Safety** 
- Other Issues 
- Rad Safety Work Ctl Form 
- Lock and Tag 
- PPS Interlocked 
- Atmospheric Work Control Form 
- Electric Sys Work Ctl Form 
- Additional Safety Information 
**Requirements** 
- Access Requirements 
- Specify Requirements 
- Beam Requirements 
- Beam Comment 
- Invasive 
- Invasive Comment 
**Status** 
- Release Conditions Defined 
**Other** 
- Safety Issue 
- Number of Persons 
- Ongoing 
- Minimum Hours 
- Person Hours 
- Toco Time 
- Feedback Priority 
- Micro 
- Primary 
- Micro Other 
- Visual Number 
**Comments** 
- Misc Job Comments 
- Feedback Priority Comment

**Comment by bisegni** [comment]
done
