### ISSUE TITLE
Update query for GET work

### ISSUE THREAD

**Issue by tiffany-slac** [eed-web-application/core-work-management#90]
additional filters for the GET /v1/work
- assignedTouserId = this will allow the creation of a personalized dashboard for the user to see the caters assigned to them
- createdBy userId = this will allow the creation of a personalized dashboard for the user to see the caters they created
- workflow request = this filter will get all the work from every domain and every worktype that uses the request workflow. basically i need a way to get all the "jobs" so users can see and drag into bucket

**Comment by bisegni** [comment]
for ```workflow request``` could be better to filter for ```workflow name```? rememebr that each workflow has a different id per domain so all workflow with the same name has differente ID and in future we could have differente ```request``` workflow

**Comment by tiffany-slac** [comment]
yes that could be better to use workflow name as they may have different ids and we need the request flow from all domains

**Comment by bisegni** [comment]
i will filter for that:
```
  @Schema(description = "Filter by users that created the work")
  List<String> createdBy,
  @Schema(description = "Filter by users that are assigned to the work")
  List<String> assignedTo,
  @Schema(description = "Filter by workflow name")
  List<String> workflowName,
  @Schema(description = "Filter by workflow state")
  List<WorkflowStateDTO> workflowState
```
